export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function WorkLayout({ children }) {
  return (
    <section>
      {children}
    </section>
  );
}