// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Nav from "@/components/Nav";
// import { ViewTransitions } from "next-view-transitions";
// import LoadingScreen from "@/components/LoadingScreen";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//       <ViewTransitions>
//     <html lang="en" className={geistSans.className}>
//       <body>
//         <LoadingScreen />
//           <Nav />
//           {children}
      
//       </body>
//     </html>
//       </ViewTransitions>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { ViewTransitions } from "next-view-transitions";
import { LoadingProvider } from "@/components/LoadingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en" className={geistSans.className}>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <LoadingProvider>
            <Nav />
            {children}
          </LoadingProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
