// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Nav from "@/components/Nav";
// import { ViewTransitions } from "next-view-transitions";
// import LoadingScreen from "@/components/LoadingScreen";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//       <ViewTransitions>
//     <html lang="en" className={geistSans.className}>
//       <body>
//         <LoadingScreen />
//           <Nav />
//           {children}
      
//       </body>
//     </html>
//       </ViewTransitions>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { ViewTransitions } from "next-view-transitions";
import { LoadingProvider } from "@/components/LoadingProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Portfolio',
  icons: {
    icon: '/logo2.png', 
  },
}

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en" className={inter.className}>
        <body className={inter.variable}>
          <LoadingProvider>
            <Nav />
            {children}
          </LoadingProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
